- name: "CH01 리팩터링: 첫 번째 예시"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > CH01 리팩터링: 첫 번째 예시"

- name: "CH02 리팩터링 원칙"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > CH02 리팩터링 원칙"

- name: "CH03 코드에서 나는 악취"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > CH03 코드에서 나는 악취"

- name: "CH04 테스트 구축하기"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > CH04 테스트 구축하기"

- name: "CH05 리팩터링 카탈로그 보는 법"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > CH05 리팩터링 카탈로그 보는 법"

- name: "CH06 기본적인 리팩터링"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH06 기본적인 리팩터링"

- name: "CH07 캡슐화"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH07 캡슐화"

- name: "CH08 기능 이동"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH08 기능 이동"

- name: "CH09 데이터 조직화"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH09 데이터 조직화"

- name: "CH10 조건부 로직 간소화"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH10 조건부 로직 간소화"

- name: "CH11 API 리팩터링"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH11 API 리팩터링"

- name: "CH12 상속 다루기"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > CH12 상속 다루기"