- name: "[1장] 리팩터링: 첫 번째 예시"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > [1장] 리팩터링: 첫 번째 예시"

- name: "[2장] 리팩터링 원칙"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > [2장] 리팩터링 원칙"

- name: "[3장] 코드에서 나는 악취"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > [3장] 코드에서 나는 악취"

- name: "[4장] 테스트 구축하기"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > [4장] 테스트 구축하기"

- name: "[5장] 리팩터링 카탈로그 보는 법"
  color: "0366d6"
  description: "PART 1 리팩터링 기초 > [5장] 리팩터링 카탈로그 보는 법"

- name: "[6장] 기본적인 리팩터링"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [6장] 기본적인 리팩터링"

- name: "[7장] 캡슐화"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [7장] 캡슐화"

- name: "[8장] 기능 이동"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [8장] 기능 이동"

- name: "[9장] 데이터 조직화"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [9장] 데이터 조직화"

- name: "[10장] 조건부 로직 간소화"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [10장] 조건부 로직 간소화"

- name: "[11장] API 리팩터링"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [11장] API 리팩터링"

- name: "[12장] 상속 다루기"
  color: "0E8A16"
  description: "PART 2 리팩터링 기법(카탈로그) > [12장] 상속 다루기"