# PART 1 - 리액트 기본 개념
- name: "PART 1 리액트 기본 개념"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념"

- name: "1장 리액트 안티패턴 소개"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 1장 리액트 안티패턴 소개"

- name: "1.1 UI 구축의 어려움에 대한 이해"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 1장 리액트 안티패턴 소개 > 1.1 UI 구축의 어려움에 대한 이해"

- name: "1.2 상태 관리의 이해"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 1장 리액트 안티패턴 소개 > 1.2 상태 관리의 이해"

- name: "1.3 예외 흐름 탐색하기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 1장 리액트 안티패턴 소개 > 1.3 예외 흐름 탐색하기"

- name: "1.4 리액트의 일반적인 안티패턴 살펴보기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 1장 리액트 안티패턴 소개 > 1.4 리액트의 일반적인 안티패턴 살펴보기"

- name: "2장 리액트 필수 개념 이해"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해"

- name: "2.1 리액트 정적 컴포넌트"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해 > 2.1 리액트 정적 컴포넌트"

- name: "2.2 prop이 있는 컴포넌트 만들기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해 > 2.2 prop이 있는 컴포넌트 만들기"

- name: "2.3 UI를 여러 컴포넌트로 나누기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해 > 2.3 UI를 여러 컴포넌트로 나누기"

- name: "2.4 리액트 내부 상태 관리"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해 > 2.4 리액트 내부 상태 관리"

- name: "2.5 렌더링 과정 이해하기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해 > 2.5 렌더링 과정 이해하기"

- name: "2.6 많이 사용되는 리액트 훅"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 2장 리액트 필수 개념 이해 > 2.6 많이 사용되는 리액트 훅"

- name: "3장 리액트 애플리케이션 구조"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 3장 리액트 애플리케이션 구조"

- name: "3.1 구조화되지 않은 프로젝트의 문제점"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 3장 리액트 애플리케이션 구조 > 3.1 구조화되지 않은 프로젝트의 문제점"

- name: "3.2 프런트엔드 애플리케이션의 복잡함에 대한 이해"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 3장 리액트 애플리케이션 구조 > 3.2 프런트엔드 애플리케이션의 복잡함에 대한 이해"

- name: "3.3 일반적인 리액트 애플리케이션 구조"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 3장 리액트 애플리케이션 구조 > 3.3 일반적인 리액트 애플리케이션 구조"

- name: "3.4 프로젝트 구조를 체계적으로 유지하기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 3장 리액트 애플리케이션 구조 > 3.4 프로젝트 구조를 체계적으로 유지하기"

- name: "4장 리액트 컴포넌트 설계하기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 4장 리액트 컴포넌트 설계하기"

- name: "4.1 단일 책임 원칙"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 4장 리액트 컴포넌트 설계하기 > 4.1 단일 책임 원칙"

- name: "4.2 중복 배제 원칙"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 4장 리액트 컴포넌트 설계하기 > 4.2 중복 배제 원칙"

- name: "4.3 합성 활용하기"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 4장 리액트 컴포넌트 설계하기 > 4.3 합성 활용하기"

- name: "4.4 컴포넌트 설계 원칙의 결합"
  color: "0366d6"
  description: "PART 1 리액트 기본 개념 > 4장 리액트 컴포넌트 설계하기 > 4.4 컴포넌트 설계 원칙의 결합"

# PART 2 - 테스팅 기법
- name: "PART 2 테스팅 기법"
  color: "5319E7"
  description: "PART 2 테스팅 기법"

- name: "5장 리액트 테스팅"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 5장 리액트 테스팅"

- name: "5.1 테스트가 필요한 이유"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 5장 리액트 테스팅 > 5.1 테스트가 필요한 이유"

- name: "5.2 여러 종류의 테스트 알아보기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 5장 리액트 테스팅 > 5.2 여러 종류의 테스트 알아보기"

- name: "5.3 Jest로 하는 개별 단위 테스팅"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 5장 리액트 테스팅 > 5.3 Jest로 하는 개별 단위 테스팅"

- name: "5.4 통합 테스트"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 5장 리액트 테스팅 > 5.4 통합 테스트"

- name: "5.5 Cypress를 이용한 E2E 테스트"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 5장 리액트 테스팅 > 5.5 Cypress를 이용한 E2E 테스트"

- name: "6장 일반적인 리팩터링 기법 살펴보기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기"

- name: "6.1 리팩터링 이해하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.1 리팩터링 이해하기"

- name: "6.2 리팩터링 전 테스트 추가하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.2 리팩터링 전 테스트 추가하기"

- name: "6.3 변수 추출하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.3 변수 추출하기"

- name: "6.4 반복문을 파이프라인으로 바꾸기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.4 반복문을 파이프라인으로 바꾸기"

- name: "6.5 함수 추출하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.5 함수 추출하기"

- name: "6.6 매개변수 객체 도입"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.6 매개변수 객체 도입"

- name: "6.7 조건문 분해하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.7 조건문 분해하기"

- name: "6.8 함수 이동하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 6장 일반적인 리팩터링 기법 살펴보기 > 6.8 함수 이동하기"

- name: "7장 리액트에서의 테스트 주도 개발"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발"

- name: "7.1 TDD 이해하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.1 TDD 이해하기"

- name: "7.2 태스킹 이해하기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.2 태스킹 이해하기"

- name: "7.3 온라인 피자 가게 애플리케이션"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.3 온라인 피자 가게 애플리케이션"

- name: "7.4 애플리케이션 요구사항 세분화"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.4 애플리케이션 요구사항 세분화"

- name: "7.5 애플리케이션 헤드라인 구현"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.5 애플리케이션 헤드라인 구현"

- name: "7.6 메뉴 목록 구현"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.6 메뉴 목록 구현"

- name: "7.7 장바구니 만들기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.7 장바구니 만들기"

- name: "7.8 장바구니에 아이템 담기"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.8 장바구니에 아이템 담기"

- name: "7.9 애플리케이션 리팩터링"
  color: "5319E7"
  description: "PART 2 테스팅 기법 > 7장 리액트에서의 테스트 주도 개발 > 7.9 애플리케이션 리팩터링"

# PART 3 - 비즈니스 로직과 디자인 패턴
- name: "PART 3 비즈니스 로직과 디자인 패턴 알아보기"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기"

- name: "8장 리액트 데이터 관리"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 8장 리액트 데이터 관리"

- name: "8.1 비즈니스 로직 누수 현상"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 8장 리액트 데이터 관리 > 8.1 비즈니스 로직 누수 현상"

- name: "8.2 ACL(오류 방지 계층)"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 8장 리액트 데이터 관리 > 8.2 ACL(오류 방지 계층)"

- name: "8.3 Prop Drilling 문제 살펴보기"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 8장 리액트 데이터 관리 > 8.3 Prop Drilling 문제 살펴보기"

- name: "8.4 Context API를 통한 Prop Drilling 문제 해결"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 8장 리액트 데이터 관리 > 8.4 Context API를 통한 Prop Drilling 문제 해결"

- name: "9장 리액트 설계 원칙 적용"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 9장 리액트 설계 원칙 적용"

- name: "9.1 단일 책임 원칙"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 9장 리액트 설계 원칙 적용 > 9.1 단일 책임 원칙"

- name: "9.2 의존관계 역전 원칙"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 9장 리액트 설계 원칙 적용 > 9.2 의존관계 역전 원칙"

- name: "9.3 명령과 조회 책임 분리 원칙"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 9장 리액트 설계 원칙 적용 > 9.3 명령과 조회 책임 분리 원칙"

- name: "10장 합성 패턴"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 10장 합성 패턴"

- name: "10.1 고차 컴포넌트를 통한 합성의 이해"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 10장 합성 패턴 > 10.1 고차 컴포넌트를 통한 합성의 이해"

- name: "10.2 리액트 훅"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 10장 합성 패턴 > 10.2 리액트 훅"

- name: "10.3 드롭다운 목록 컴포넌트 만들기"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 10장 합성 패턴 > 10.3 드롭다운 목록 컴포넌트 만들기"

- name: "10.4 헤드리스 컴포넌트 패턴"
  color: "0E8A16"
  description: "PART 3 비즈니스 로직과 디자인 패턴 알아보기 > 10장 합성 패턴 > 10.4 헤드리스 컴포넌트 패턴"

# PART 4 - 실무에서의 구현
- name: "PART 4 실무에서의 구현"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현"

- name: "11장 리액트 계층 구조 애플리케이션"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 11장 리액트 계층 구조 애플리케이션"

- name: "11.1 리액트 애플리케이션의 진화"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 11장 리액트 계층 구조 애플리케이션 > 11.1 리액트 애플리케이션의 진화"

- name: "11.2 코드 오븐 애플리케이션 개선하기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 11장 리액트 계층 구조 애플리케이션 > 11.2 코드 오븐 애플리케이션 개선하기"

- name: "11.3 장바구니 컴포넌트 구현"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 11장 리액트 계층 구조 애플리케이션 > 11.3 장바구니 컴포넌트 구현"

- name: "11.4 계층 구조 알아보기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 11장 리액트 계층 구조 애플리케이션 > 11.4 계층 구조 알아보기"

- name: "12장 E2E 프로젝트 구현하기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기"

- name: "12.1 날씨 애플리케이션에 필요한 요구사항 확인"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기 > 12.1 날씨 애플리케이션에 필요한 요구사항 확인"

- name: "12.2 초기 승인 테스트 작성"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기 > 12.2 초기 승인 테스트 작성"

- name: "12.3 도시 검색 기능 구현"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기 > 12.3 도시 검색 기능 구현"

- name: "12.4 ACL 구현"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기 > 12.4 ACL 구현"

- name: "12.5 즐겨찾기 추가 기능 구현"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기 > 12.5 즐겨찾기 추가 기능 구현"

- name: "12.6 애플리케이션 재실행 시 이전 날씨 데이터 불러오기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 12장 E2E 프로젝트 구현하기 > 12.6 애플리케이션 재실행 시 이전 날씨 데이터 불러오기"

- name: "13장 리액트 안티패턴 원칙 돌아보기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 13장 리액트 안티패턴 원칙 돌아보기"

- name: "13.1 일반적인 안티패턴 돌아보기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 13장 리액트 안티패턴 원칙 돌아보기 > 13.1 일반적인 안티패턴 돌아보기"

- name: "13.2 디자인 패턴 훑어보기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 13장 리액트 안티패턴 원칙 돌아보기 > 13.2 디자인 패턴 훑어보기"

- name: "13.3 기본 설계 원칙 복습하기"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 13장 리액트 안티패턴 원칙 돌아보기 > 13.3 기본 설계 원칙 복습하기"

- name: "13.4 기법과 실무 예제 정리"
  color: "D93F0B"
  description: "PART 4 실무에서의 구현 > 13장 리액트 안티패턴 원칙 돌아보기 > 13.4 기법과 실무 예제 정리"
