name: Auto Reviewers

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

# 권한을 명시적으로 추가
permissions:
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      